export const ADD_PERSON_TO_FAVORITE = 'ADD_PERSONE_TO_FAVORITE';
export const REMOVE_PERSON_FROM_FAVORITE = 'REMOVE_PERSONE_FROM_FAVORITE';
export const ADD_CARDSLIST = 'ADD_CARDSLIST';
export const REMOVE_CARD = 'REMOVE_CARD';